/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.apple.schema.KVS.avro;  
@SuppressWarnings("all")
/** Avro storing with schema using Pig. */
public class AggrDailyAvroEntity1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"AggrDailyAvroEntity\",\"namespace\":\"com.apple.schema.KVS.avro.\",\"doc\":\"Avro storing with schema using Pig.\",\"fields\":[{\"name\":\"LATEST_USED_STORAGE_SIZE_DLY\",\"type\":[\"null\",\"long\"]},{\"name\":\"AGGR_COUNT_DLY\",\"type\":[\"null\",\"long\"]},{\"name\":\"PRS_ID\",\"type\":[\"null\",\"long\"]},{\"name\":\"UD_ID\",\"type\":[\"null\",\"string\"]},{\"name\":\"EVENT_TYPE\",\"type\":[\"null\",\"string\"]},{\"name\":\"PLATFORM\",\"type\":[\"null\",\"string\"]},{\"name\":\"OS_VERSION\",\"type\":[\"null\",\"string\"]},{\"name\":\"APPLICATION\",\"type\":[\"null\",\"string\"]},{\"name\":\"BUNDLE_ID\",\"type\":[\"null\",\"string\"]},{\"name\":\"KV_ID\",\"type\":[\"null\",\"string\"]},{\"name\":\"SERVER_ERROR\",\"type\":[\"null\",\"string\"]},{\"name\":\"SERVICE_TYPE\",\"type\":[\"null\",\"string\"]},{\"name\":\"EVENT_DATE_1\",\"type\":[\"null\",\"string\"]},{\"name\":\"EVENT_DATE_2\",\"type\":[\"null\",\"string\"]},{\"name\":\"EVENT_TIME_EPOCH\",\"type\":[\"null\",\"long\"]}]}");
  public Long LATEST_USED_STORAGE_SIZE_DLY;
  public Long AGGR_COUNT_DLY;
  public Long PRS_ID;
  public CharSequence UD_ID;
  public CharSequence EVENT_TYPE;
  public CharSequence PLATFORM;
  public CharSequence OS_VERSION;
  public CharSequence APPLICATION;
  public CharSequence BUNDLE_ID;
  public CharSequence KV_ID;
  public CharSequence SERVER_ERROR;
  public CharSequence SERVICE_TYPE;
  public CharSequence EVENT_DATE_1;
  public CharSequence EVENT_DATE_2;
  public Long EVENT_TIME_EPOCH;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return LATEST_USED_STORAGE_SIZE_DLY;
    case 1: return AGGR_COUNT_DLY;
    case 2: return PRS_ID;
    case 3: return UD_ID;
    case 4: return EVENT_TYPE;
    case 5: return PLATFORM;
    case 6: return OS_VERSION;
    case 7: return APPLICATION;
    case 8: return BUNDLE_ID;
    case 9: return KV_ID;
    case 10: return SERVER_ERROR;
    case 11: return SERVICE_TYPE;
    case 12: return EVENT_DATE_1;
    case 13: return EVENT_DATE_2;
    case 14: return EVENT_TIME_EPOCH;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: LATEST_USED_STORAGE_SIZE_DLY = (Long)value$; break;
    case 1: AGGR_COUNT_DLY = (Long)value$; break;
    case 2: PRS_ID = (Long)value$; break;
    case 3: UD_ID = (CharSequence)value$; break;
    case 4: EVENT_TYPE = (CharSequence)value$; break;
    case 5: PLATFORM = (CharSequence)value$; break;
    case 6: OS_VERSION = (CharSequence)value$; break;
    case 7: APPLICATION = (CharSequence)value$; break;
    case 8: BUNDLE_ID = (CharSequence)value$; break;
    case 9: KV_ID = (CharSequence)value$; break;
    case 10: SERVER_ERROR = (CharSequence)value$; break;
    case 11: SERVICE_TYPE = (CharSequence)value$; break;
    case 12: EVENT_DATE_1 = (CharSequence)value$; break;
    case 13: EVENT_DATE_2 = (CharSequence)value$; break;
    case 14: EVENT_TIME_EPOCH = (Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  
}
